### ISSUE TITLE
Module not working

### ISSUE THREAD

**Issue by m1ga** [AppWerft/Ti.VRView#1]
```javascript
var VR = require("ti.vrview");
var win = Ti.UI.createWindow({});
var panoView = VR.createPanoramaView({
	type: VR.TYPE_MONO,
	image: Ti.Filesystem.getFile(Ti.Filesystem.applicationDataDirectory, "pano.jpg"),
	onload: function() {},
	onchanged: function(e) {
		console.log(e.yaw);
		console.log(e.pitch);
	},
	fullscreenButtonEnabled: false,
	infoButtonEnabled: false,
	stereoModeButtonEnabled: false,
	touchTrackingEnabled: true,
	transitionViewEnabled: false,
	sensorDelay: VR.SENSOR_DELAY_NORMAL
});
win.add(panoView);
win.open();
```

`fileUriOfPanoImage` at this line is empty and the app will crash:
https://github.com/AppWerft/Ti.VRView/blob/master/android/src/ti/vrview/PanoramaViewProxy.java#L89

Also there is an extra `)` in 
https://github.com/AppWerft/Ti.VRView/blame/master/README.md#L27

and the `win.open()` is missing in the code inside the README

It looks like the whole `handleCreationDict` is not working; when I put a log in there it won't show anything

**Comment by AppWerft** [comment]
Before you access asset in app folder you need to copy:

var image = Ti.Filesystem.getFile(Ti.Filesystem.applicationDataDirectory, "pano.jpg");
image.write(Ti.Filesystem.getFile(Ti.Filesystem.resourcesDirectory, "pano.jpg").read());

**Comment by m1ga** [comment]
Thanks! Working fine now.
